### ISSUE TITLE
Doesn't work under Python 3

### ISSUE THREAD

**Issue by Jajcus** [rayed/pyagentx#7]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/share/python3.4/site-packages/pyagentx/__init__.py", line 6, in <module>
    from pyagentx.updater import Updater
  File "/usr/share/python3.4/site-packages/pyagentx/updater.py", line 15, in <module>
    import Queue
ImportError: No module named 'Queue'
```

Hello… it is year 2015.

**Comment by rayed** [comment]
Thank you for your feedback, do you have a patch?

**Comment by rayed** [comment]
Check "python3" brach for a fix, please confirm!

**Comment by tracernz** [comment]
This branch works for me on python 3.6.4. Any chance you can merge it to master, and make a new release to PyPi? Otherwise this isn't really usable as a dep.

**Comment by rayed** [comment]
I haven't used this software for a while, and obviously I can't maintain it!

Would you care to fork it and maintain it!

**Comment by tracernz** [comment]
I'll think about it for a couple of days. It's a really nice little library that does exactly what I want (great work! 😁), but I'm only using it for a tiny util on one machine (providing hwmon temperature sensors on an ODroid C2 running mainline kernel), so I'm concerned it wouldn't get the attention it deserves.
